# Generated by Django 3.2.8 on 2021-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realizacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Realizacje',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
