# Generated by Django 3.2.8 on 2021-11-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Marki',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.AlterModelOptions(
            name='tuz',
            options={'verbose_name': 'Wszystkie tuzy', 'verbose_name_plural': 'Wszystkie tuzy'},
        ),
        migrations.RemoveField(
            model_name='tuz',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tuz',
            name='rozmiar',
        ),
        migrations.RemoveField(
            model_name='tuz',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tuz',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='tuz',
            name='waga',
        ),
        migrations.AddField(
            model_name='tuz',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tuz',
            name='marka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tuzy.marka'),
            preserve_default=False,
        ),
    ]
