# Generated by Django 3.2.8 on 2021-11-04 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuzy', '0002_auto_20211102_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuz',
            name='opis',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
